"""AI-only coding problem generation using OpenAI-compatible APIs."""

from __future__ import annotations

import asyncio
import json
import logging
import random
import re
import threading
from queue import Queue
from typing import Optional

from openai import AsyncOpenAI, OpenAI
from pydantic import AliasChoices, BaseModel, Field

logger = logging.getLogger(__name__)


class TestCase(BaseModel):
    """Single stdin/stdout pair for a coding problem."""

    input: str = Field(default="", description="Exact stdin for the solution.")
    output: str = Field(
        description="Exact expected stdout for the solution.",
        validation_alias=AliasChoices("output", "expected_output", "expected"),
    )


class CodingProblem(BaseModel):
    """Structured coding problem generated by the endpoint."""

    title: str = Field(
        default="Generated Coding Problem",
        validation_alias=AliasChoices("title", "name"),
    )
    description: str = Field(
        validation_alias=AliasChoices("description", "problem", "statement", "prompt")
    )
    input_format: str = Field(
        default="Read from standard input.",
        validation_alias=AliasChoices("input_format", "input", "input_spec"),
    )
    output_format: str = Field(
        default="Write to standard output.",
        validation_alias=AliasChoices("output_format", "output", "output_spec"),
    )
    constraints: list[str] = Field(default_factory=list)
    examples: list[TestCase] = Field(default_factory=list)
    test_cases: list[TestCase] = Field(
        default_factory=list,
        validation_alias=AliasChoices("test_cases", "tests", "hidden_tests"),
    )


_TOPICS = [
    "arrays and hashing",
    "two pointers",
    "binary search",
    "sliding window",
    "stack and queue",
    "linked lists",
    "trees and graphs",
    "dynamic programming",
    "greedy algorithms",
    "math and number theory",
    "strings",
    "geometry and simulation",
]

_GEN_SYSTEM = (
    "You generate original programming contest style problems. "
    "Return only structured data, keep tasks deterministic, and ensure all test cases are valid. "
    "Always include these top-level fields: title, description, input_format, output_format, constraints, examples, test_cases. "
    "Each example and test case must contain input and output fields only."
)

_GEN_USER = """Generate one {difficulty} coding problem about {topic}.

Requirements:
- It must be solvable from standard input and output only.
- It must not require network, files, randomness, or user interaction.
- Return exactly these top-level keys: title, description, input_format, output_format, constraints, examples, test_cases.
- `constraints` must be a list of strings.
- `examples` must be a list of objects with `input` and `output`.
- Include exactly {n_tests} hidden test cases.
- `test_cases` must be a list of exactly {n_tests} objects with `input` and `output`.
- Keep the problem self-contained and unambiguous.
- Make outputs exact strings, preserving newlines when needed.
"""


class ProblemGenerator:
    """Generate coding problems from an OpenAI-compatible endpoint."""

    topics = tuple(_TOPICS)

    def __init__(self, base_url: str, api_key: str, model: str) -> None:
        """Create the OpenAI client wrapper."""

        self.client = OpenAI(base_url=base_url, api_key=api_key)
        self.model = model

    def generate(
        self, difficulty: str, n_tests: int, topic: str | None = None
    ) -> Optional[CodingProblem]:
        """Generate one coding problem using structured output with JSON fallback."""

        chosen_topic = topic or random.choice(_TOPICS)
        user_prompt = _GEN_USER.format(
            difficulty=difficulty, n_tests=n_tests, topic=chosen_topic
        )
        messages = [
            {"role": "system", "content": _GEN_SYSTEM},
            {"role": "user", "content": user_prompt},
        ]

        try:
            response = self.client.beta.chat.completions.parse(
                model=self.model,
                messages=messages,
                response_format=CodingProblem,
            )
            parsed = response.choices[0].message.parsed
            if parsed is not None:
                problem = CodingProblem.model_validate(parsed)
                if problem.test_cases:
                    return problem
        except Exception as exc:
            logger.warning(f"structured parse failed: {exc}")

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=messages,
                response_format={"type": "json_object"},
            )
            content = response.choices[0].message.content or ""
            clean = self._strip_fences(content)
            problem = CodingProblem.model_validate_json(clean)
            if problem.test_cases:
                return problem
        except Exception as exc:
            logger.warning(f"json fallback failed: {exc}")
        logger.error("no usable test cases were generated")
        return None

    @staticmethod
    def _strip_fences(content: str) -> str:
        """Remove optional fenced code wrappers from model output."""

        text = content.strip()
        match = re.search(r"```(?:json)?\s*(.*?)\s*```", text, re.DOTALL)
        if match:
            return match.group(1).strip()
        if text.startswith("{"):
            return text
        try:
            return json.dumps(json.loads(text))
        except Exception:
            return text


class AsyncProblemGenerator:
    """High-throughput problem generator using AsyncOpenAI and a prefetch queue."""

    def __init__(
        self,
        base_url: str,
        api_key: str,
        model: str,
        difficulty: str,
        n_tests: int,
        queue_size: int = 8,
    ) -> None:
        self.client = AsyncOpenAI(base_url=base_url, api_key=api_key)
        self.model = model
        self.difficulty = difficulty
        self.n_tests = n_tests
        self.queue: Queue[CodingProblem] = Queue(maxsize=queue_size)
        self._stop_event = threading.Event()
        self._thread = threading.Thread(target=self._run_loop, daemon=True)
        self._thread.start()

    def _run_loop(self) -> None:
        """Run the asyncio event loop in a background thread."""
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        try:
            loop.run_until_complete(self._producer())
        finally:
            loop.close()

    async def _producer(self) -> None:
        """Continuously refill the queue using async calls."""
        while not self._stop_event.is_set():
            if self.queue.full():
                await asyncio.sleep(0.1)
                continue

            # Generate a batch of problems to fill the queue
            needed = self.queue.maxsize - self.queue.qsize()
            if needed <= 0:
                await asyncio.sleep(0.1)
                continue

            tasks = [self._generate_one() for _ in range(needed)]
            results = await asyncio.gather(*tasks)

            for prob in results:
                if prob:
                    # Non-blocking put since we calculated 'needed'
                    # but use a small timeout or check just in case.
                    try:
                        self.queue.put(prob, timeout=0.1)
                    except Exception:
                        pass

    async def _generate_one(self) -> Optional[CodingProblem]:
        """Generate a single problem asynchronously."""
        topic = random.choice(_TOPICS)
        user_prompt = _GEN_USER.format(
            difficulty=self.difficulty, n_tests=self.n_tests, topic=topic
        )
        messages = [
            {"role": "system", "content": _GEN_SYSTEM},
            {"role": "user", "content": user_prompt},
        ]

        try:
            response = await self.client.beta.chat.completions.parse(
                model=self.model,
                messages=messages,
                response_format=CodingProblem,
            )
            parsed = response.choices[0].message.parsed
            if parsed is not None:
                return CodingProblem.model_validate(parsed)
        except Exception as exc:
            logger.debug(f"async structured parse failed: {exc}")

        try:
            response = await self.client.chat.completions.create(
                model=self.model,
                messages=messages,
                response_format={"type": "json_object"},
            )
            content = response.choices[0].message.content or ""
            clean = ProblemGenerator._strip_fences(content)
            return CodingProblem.model_validate_json(clean)
        except Exception as exc:
            logger.debug(f"async json fallback failed: {exc}")
        return None

    def get(self) -> CodingProblem:
        """Get the next available problem, blocking if necessary."""
        return self.queue.get()

    def stop(self) -> None:
        """Signal the producer to stop."""
        self._stop_event.set()
