"""AI-only coding problem generation using OpenAI-compatible APIs."""

from __future__ import annotations

import json
import random
import re
from typing import Optional

from openai import OpenAI
from pydantic import AliasChoices, BaseModel, Field


class TestCase(BaseModel):
    """Single stdin/stdout pair for a coding problem."""

    input: str = Field(default="", description="Exact stdin for the solution.")
    output: str = Field(
        description="Exact expected stdout for the solution.",
        validation_alias=AliasChoices("output", "expected_output", "expected"),
    )


class CodingProblem(BaseModel):
    """Structured coding problem generated by the endpoint."""

    title: str = Field(
        default="Generated Coding Problem",
        validation_alias=AliasChoices("title", "name"),
    )
    description: str = Field(
        validation_alias=AliasChoices("description", "problem", "statement", "prompt")
    )
    input_format: str = Field(
        default="Read from standard input.",
        validation_alias=AliasChoices("input_format", "input", "input_spec"),
    )
    output_format: str = Field(
        default="Write to standard output.",
        validation_alias=AliasChoices("output_format", "output", "output_spec"),
    )
    constraints: list[str] = Field(default_factory=list)
    examples: list[TestCase] = Field(default_factory=list)
    test_cases: list[TestCase] = Field(
        default_factory=list,
        validation_alias=AliasChoices("test_cases", "tests", "hidden_tests"),
    )


_TOPICS = [
    "arrays and hashing",
    "two pointers",
    "binary search",
    "sliding window",
    "stack and queue",
    "linked lists",
    "trees and graphs",
    "dynamic programming",
    "greedy algorithms",
    "math and number theory",
    "strings",
    "geometry and simulation",
]

_GEN_SYSTEM = (
    "You generate original programming contest style problems. "
    "Return only structured data, keep tasks deterministic, and ensure all test cases are valid. "
    "Always include these top-level fields: title, description, input_format, output_format, constraints, examples, test_cases. "
    "Each example and test case must contain input and output fields only."
)

_GEN_USER = """Generate one {difficulty} coding problem about {topic}.

Requirements:
- It must be solvable from standard input and output only.
- It must not require network, files, randomness, or user interaction.
- Return exactly these top-level keys: title, description, input_format, output_format, constraints, examples, test_cases.
- `constraints` must be a list of strings.
- `examples` must be a list of objects with `input` and `output`.
- Include exactly {n_tests} hidden test cases.
- `test_cases` must be a list of exactly {n_tests} objects with `input` and `output`.
- Keep the problem self-contained and unambiguous.
- Make outputs exact strings, preserving newlines when needed.
"""


class ProblemGenerator:
    """Generate coding problems from an OpenAI-compatible endpoint."""

    topics = tuple(_TOPICS)

    def __init__(self, base_url: str, api_key: str, model: str) -> None:
        """Create the OpenAI client wrapper."""

        self.client = OpenAI(base_url=base_url, api_key=api_key)
        self.model = model

    def generate(
        self, difficulty: str, n_tests: int, topic: str | None = None
    ) -> Optional[CodingProblem]:
        """Generate one coding problem using structured output with JSON fallback."""

        chosen_topic = topic or random.choice(_TOPICS)
        user_prompt = _GEN_USER.format(
            difficulty=difficulty, n_tests=n_tests, topic=chosen_topic
        )
        messages = [
            {"role": "system", "content": _GEN_SYSTEM},
            {"role": "user", "content": user_prompt},
        ]

        try:
            response = self.client.beta.chat.completions.parse(
                model=self.model,
                messages=messages,
                response_format=CodingProblem,
            )
            parsed = response.choices[0].message.parsed
            if parsed is not None:
                problem = CodingProblem.model_validate(parsed)
                if problem.test_cases:
                    return problem
        except Exception as exc:
            print(f"[generator] structured parse failed: {exc}")

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=messages,
                response_format={"type": "json_object"},
            )
            content = response.choices[0].message.content or ""
            clean = self._strip_fences(content)
            problem = CodingProblem.model_validate_json(clean)
            if problem.test_cases:
                return problem
        except Exception as exc:
            print(f"[generator] json fallback failed: {exc}")
        print("[generator] no usable test cases were generated")
        return None

    @staticmethod
    def _strip_fences(content: str) -> str:
        """Remove optional fenced code wrappers from model output."""

        text = content.strip()
        match = re.search(r"```(?:json)?\s*(.*?)\s*```", text, re.DOTALL)
        if match:
            return match.group(1).strip()
        if text.startswith("{"):
            return text
        return json.dumps(json.loads(text))
