"""AI-only coding problem generation using OpenAI-compatible APIs."""

from __future__ import annotations

import json
import random
import re
from typing import Optional

from openai import OpenAI
from pydantic import BaseModel, Field


class TestCase(BaseModel):
    """Single stdin/stdout pair for a coding problem."""

    input: str = Field(default="", description="Exact stdin for the solution.")
    output: str = Field(description="Exact expected stdout for the solution.")


class CodingProblem(BaseModel):
    """Structured coding problem generated by the endpoint."""

    title: str
    description: str
    input_format: str
    output_format: str
    constraints: list[str]
    examples: list[TestCase]
    test_cases: list[TestCase]


_TOPICS = [
    "arrays and hashing",
    "two pointers",
    "binary search",
    "sliding window",
    "stack and queue",
    "linked lists",
    "trees and graphs",
    "dynamic programming",
    "greedy algorithms",
    "math and number theory",
    "strings",
    "geometry and simulation",
]

_GEN_SYSTEM = (
    "You generate original programming contest style problems. "
    "Return only structured data, keep tasks deterministic, and ensure all test cases are valid."
)

_GEN_USER = """Generate one {difficulty} coding problem about {topic}.

Requirements:
- It must be solvable from standard input and output only.
- It must not require network, files, randomness, or user interaction.
- Include exactly {n_tests} hidden test cases.
- Keep the problem self-contained and unambiguous.
- Make outputs exact strings, preserving newlines when needed.
"""


class ProblemGenerator:
    """Generate coding problems from an OpenAI-compatible endpoint."""

    topics = tuple(_TOPICS)

    def __init__(self, base_url: str, api_key: str, model: str) -> None:
        """Create the OpenAI client wrapper."""

        self.client = OpenAI(base_url=base_url, api_key=api_key)
        self.model = model

    def generate(
        self, difficulty: str, n_tests: int, topic: str | None = None
    ) -> Optional[CodingProblem]:
        """Generate one coding problem using structured output with JSON fallback."""

        chosen_topic = topic or random.choice(_TOPICS)
        user_prompt = _GEN_USER.format(
            difficulty=difficulty, n_tests=n_tests, topic=chosen_topic
        )
        messages = [
            {"role": "system", "content": _GEN_SYSTEM},
            {"role": "user", "content": user_prompt},
        ]

        try:
            response = self.client.beta.chat.completions.parse(
                model=self.model,
                messages=messages,
                response_format=CodingProblem,
            )
            parsed = response.choices[0].message.parsed
            if parsed is not None:
                return parsed
        except Exception as exc:
            print(f"[generator] structured parse failed: {exc}")

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=messages,
                response_format={"type": "json_object"},
            )
            content = response.choices[0].message.content or ""
            clean = self._strip_fences(content)
            return CodingProblem.model_validate_json(clean)
        except Exception as exc:
            print(f"[generator] json fallback failed: {exc}")
            return None

    @staticmethod
    def _strip_fences(content: str) -> str:
        """Remove optional fenced code wrappers from model output."""

        text = content.strip()
        match = re.search(r"```(?:json)?\s*(.*?)\s*```", text, re.DOTALL)
        if match:
            return match.group(1).strip()
        if text.startswith("{"):
            return text
        return json.dumps(json.loads(text))
